name: Publish

on: workflow_dispatch

jobs:
  Publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: corretto
          architecture: x64

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run linters and unit tests
        run: ./gradlew check --stacktrace

      - name: Publish test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests
        if: ${{ failure() }}

      - name: Publish JAR
        run: ./gradlew publish --stacktrace
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
